name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.3.2
  - numpy=1.19.2
  - python=3.8
  - pywavelets=1.1.1
  - scipy=1.5.2
  - seaborn=0.11.0
  - tqdm=4.50.2
  - pip=20.2.4
  - pip:
    - colorednoise==1.1.1
    - pycwt==0.3.0a22
